# Generated by Django 2.1.3 on 2018-11-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Writings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('category', models.TextField()),
                ('administration', models.CharField(max_length=100)),
                ('legislature', models.CharField(max_length=100)),
                ('keywords', models.TextField()),
            ],
        ),
    ]
